---
title: "My First Quarto Upload!"
subtitle: "`r paste0('Last rendered: ', Sys.Date())`"
author: "Daniel Amieva Rodriguez"
format: 
  html:
    embed-resources: true
    code-fold: true
editor: visual
---

## Demo Grid Layout with Cats and Other Rtsy Stuff

```{r}
#| label: load-packages
#| include: false
install.packages("rmarkdown")
library(magick)
library(reticulate)
here::i_am("gridlayout_demo.qmd")
```

```{r}
#| label: load-images
#| include: false
obtuse_cat <- image_read("https://wallpapercave.com/wp/wp2618926.jpg")
cat_n_roses <- image_read("https://2.bp.blogspot.com/-WdjaYnmHI1k/T9uf0rOp3gI/AAAAAAAAAEQ/fQ_FjVKRlmA/s1600/Cute-Cats-011.jpg")
cat_buquet <- image_read("https://i.pinimg.com/originals/89/35/1f/89351f7cba1f094ffb8ecd6476a90e7f.jpg")
```

::: {#tab-cats .panel-tabset}
## Cat 1

```{r printcat1}
obtuse_cat
```

## Chonk 2

```{r printcat2}
cat_n_roses
```

## Chonk 3

```{r printcat3}
cat_buquet
```
:::

## Having Plots side by side

### Using Python

```{python}
#| label: fig-charts
#| fig-cap: "Charts"
#| fig-subcap: 
#|   - "Left"
#|   - "Right"
#| layout-ncol: 2

import matplotlib.pyplot as plt
plt.plot([1,23,2,4])
plt.show()

plt.plot([8,65,23,90])
plt.show()
```

### Using R

Getting artsy

```{r}
#| label: fig-artsy-artworks
#| fig-cap: "Generative Art"
#| fig-subcap: 
#|  - "Favorite Random Image 1"
#|  - "Favorite Random Image 2"
#|  - "Random Palette"
#|  - "Divergent Palette"
#| layout-ncol: 2
#| layout-nrow: 2
library(aRtsy)
library(magick)
library(grid)
artwork_nebula_random <- canvas_nebula(colors = colorPalette("random", n=8))
artwork_nebula_random

artwork_nebula_divergent <- canvas_nebula(colors = colorPalette("divergent", n=4))
artwork_nebula_divergent

images_2_choose <- fs::dir_ls(here::here('rstsy outputs/refined outputs'))

images_rand_chosen <- sample(images_2_choose, 2)

favorite_random_image1 <- image_read(images_rand_chosen[1])
favorite_random_image2 <- image_read(images_rand_chosen[2])


favorite_random_image1
favorite_random_image2
```
